// ─── BANCO DE CARTAS DO 30 SEGUNDOS ────────────────────────────────────
// Isolado do jogos.js de propósito: são só dados (~200 cartas), não
// lógica de jogo — deixa o jogos.js focado em regras, e esse arquivo fica
// fácil de revisar/editar/adicionar cartas sem mexer em código.
//
// Cada carta tem:
//  - palavra:   a resposta certa (sempre em minúsculas, sem acento é OK
//               também — a checagem de acerto já ignora acento/maiúscula)
//  - categoria: usada como contexto pro prompt da IA (Groq) gerar a dica
//  - dica:      dica de RESERVA, escrita à mão — só é usada se a Groq não
//               estiver configurada, falhar, ou demorar demais
//
// Filmes e jogos eletrônicos entram só pelo NOME (título) — são fatos,
// não reprodução de roteiro/arte de ninguém — com uma dica bem genérica,
// do jeito que qualquer jogo de perguntas e respostas faz.

const BANCO_30S = [
    // ── Animais ──
    { palavra: 'cachorro', categoria: 'animal', dica: 'o melhor amigo do homem, late e abana o rabo' },
    { palavra: 'elefante', categoria: 'animal', dica: 'o maior animal terrestre, tem uma tromba enorme' },
    { palavra: 'gato', categoria: 'animal', dica: 'animal de estimação que mia e adora dormir o dia todo' },
    { palavra: 'girafa', categoria: 'animal', dica: 'animal africano com o pescoço mais comprido do mundo' },
    { palavra: 'leao', categoria: 'animal', dica: 'considerado o rei da selva, tem uma juba enorme' },
    { palavra: 'tigre', categoria: 'animal', dica: 'felino grande com listras laranja e pretas' },
    { palavra: 'macaco', categoria: 'animal', dica: 'primata que adora bananas e pula de galho em galho' },
    { palavra: 'aranha', categoria: 'animal', dica: 'bicho de oito pernas que tece teias' },
    { palavra: 'polvo', categoria: 'animal', dica: 'animal marinho com oito tentáculos e solta tinta' },
    { palavra: 'pinguim', categoria: 'animal', dica: 'ave que não voa, vive no gelo e anda bamboleando' },
    { palavra: 'canguru', categoria: 'animal', dica: 'animal australiano que pula e carrega o filhote numa bolsa' },
    { palavra: 'tubarao', categoria: 'animal', dica: 'peixe grande e temido, cheio de dentes afiados' },
    { palavra: 'borboleta', categoria: 'animal', dica: 'inseto colorido que já foi lagarta antes' },
    { palavra: 'coruja', categoria: 'animal', dica: 'ave que enxerga bem à noite e gira bastante a cabeça' },
    { palavra: 'camelo', categoria: 'animal', dica: 'animal do deserto com corcova(s) nas costas' },
    { palavra: 'morcego', categoria: 'animal', dica: 'único mamífero que voa de verdade, se guia por ecolocalização' },
    { palavra: 'esquilo', categoria: 'animal', dica: 'bichinho pequeno que guarda nozes e tem um rabo peludo' },
    { palavra: 'jacare', categoria: 'animal', dica: 'réptil de rio com mandíbula forte e escamas grossas' },
    { palavra: 'tartaruga', categoria: 'animal', dica: 'réptil bem lento que carrega a casa nas costas' },
    { palavra: 'abelha', categoria: 'animal', dica: 'inseto que faz mel e pode picar quando se sente ameaçado' },

    // ── Natureza e fenômenos ──
    { palavra: 'vulcao', categoria: 'natureza', dica: 'montanha que às vezes cospe lava' },
    { palavra: 'tsunami', categoria: 'natureza', dica: 'onda gigante que pode destruir uma cidade litorânea' },
    { palavra: 'tempestade', categoria: 'natureza', dica: 'chuva forte com trovões e raios' },
    { palavra: 'iceberg', categoria: 'natureza', dica: 'bloco de gelo gigante flutuando no mar' },
    { palavra: 'tornado', categoria: 'natureza', dica: 'vento girando muito forte em forma de funil' },
    { palavra: 'terremoto', categoria: 'natureza', dica: 'o chão treme forte de repente' },
    { palavra: 'arco-iris', categoria: 'natureza', dica: 'aparece no céu depois da chuva, cheio de cores' },
    { palavra: 'avalanche', categoria: 'natureza', dica: 'muita neve descendo a montanha de uma vez' },
    { palavra: 'eclipse', categoria: 'natureza', dica: 'quando o sol ou a lua ficam escondidos por um momento' },
    { palavra: 'furacao', categoria: 'natureza', dica: 'tempestade giratória gigante que se forma sobre o mar' },
    { palavra: 'deserto', categoria: 'natureza', dica: 'lugar seco, cheio de areia e quase sem água' },
    { palavra: 'geleira', categoria: 'natureza', dica: 'massa enorme de gelo que se move bem devagar' },
    { palavra: 'mare', categoria: 'natureza', dica: 'o mar sobe e desce na praia por causa disso' },
    { palavra: 'labareda', categoria: 'natureza', dica: 'língua de fogo bem alta' },
    { palavra: 'aurora boreal', categoria: 'natureza', dica: 'luzes coloridas que dançam no céu perto dos polos' },

    // ── Criaturas e fantasia ──
    { palavra: 'dinossauro', categoria: 'criatura', dica: 'bicho gigante que já foi extinto há milhões de anos' },
    { palavra: 'pirata', categoria: 'pessoa', dica: 'navegador que rouba tesouros e usa tapa-olho' },
    { palavra: 'vampiro', categoria: 'criatura', dica: 'criatura da noite que tem medo de alho e sol' },
    { palavra: 'sereia', categoria: 'criatura', dica: 'metade mulher, metade peixe, vive no mar' },
    { palavra: 'fantasma', categoria: 'criatura', dica: 'espírito assombrado, atravessa paredes' },
    { palavra: 'unicornio', categoria: 'criatura', dica: 'cavalo mágico com um chifre na testa' },
    { palavra: 'zumbi', categoria: 'criatura', dica: 'morto-vivo que anda devagar atrás de gente' },
    { palavra: 'robo', categoria: 'objeto', dica: 'máquina que imita ações humanas' },
    { palavra: 'bruxa', categoria: 'criatura', dica: 'faz feitiços e costuma andar de vassoura' },
    { palavra: 'duende', categoria: 'criatura', dica: 'criatura pequena da floresta, geralmente travessa' },
    { palavra: 'dragao', categoria: 'criatura', dica: 'réptil gigante e mágico que cospe fogo' },
    { palavra: 'lobisomem', categoria: 'criatura', dica: 'pessoa que vira lobo nas noites de lua cheia' },
    { palavra: 'genio da lampada', categoria: 'criatura', dica: 'concede três desejos a quem esfrega o objeto certo' },
    { palavra: 'alienigena', categoria: 'criatura', dica: 'ser vindo de outro planeta' },
    { palavra: 'fada', categoria: 'criatura', dica: 'criatura pequena e mágica, geralmente com asas' },

    // ── Objetos do dia a dia ──
    { palavra: 'guitarra', categoria: 'objeto', dica: 'instrumento de cordas que os roqueiros adoram tocar' },
    { palavra: 'foguete', categoria: 'objeto', dica: 'sobe até o espaço soltando fogo por baixo' },
    { palavra: 'coroa', categoria: 'objeto', dica: 'reis e rainhas usam isso na cabeça' },
    { palavra: 'espada', categoria: 'objeto', dica: 'arma antiga afiada, usada em duelos e batalhas' },
    { palavra: 'trombone', categoria: 'objeto', dica: 'instrumento de sopro que estica e encolhe' },
    { palavra: 'bussola', categoria: 'objeto', dica: 'aparelho que sempre aponta pro norte' },
    { palavra: 'geladeira', categoria: 'objeto', dica: 'aparelho da cozinha que mantém a comida fria' },
    { palavra: 'telefone', categoria: 'objeto', dica: 'aparelho usado pra ligar e falar com alguém à distância' },
    { palavra: 'guarda-chuva', categoria: 'objeto', dica: 'abre pra proteger da chuva' },
    { palavra: 'oculos', categoria: 'objeto', dica: 'ajuda quem não enxerga bem' },
    { palavra: 'relogio', categoria: 'objeto', dica: 'mostra as horas, pode ser de pulso ou de parede' },
    { palavra: 'tesoura', categoria: 'objeto', dica: 'ferramenta de duas lâminas, usada pra cortar papel ou cabelo' },
    { palavra: 'escada', categoria: 'objeto', dica: 'usada pra subir ou descer quando não tem elevador' },
    { palavra: 'extintor de incendio', categoria: 'objeto', dica: 'objeto vermelho usado pra apagar fogo' },
    { palavra: 'lampada', categoria: 'objeto', dica: 'ilumina o ambiente quando ligada na tomada' },
    { palavra: 'chave', categoria: 'objeto', dica: 'usada pra abrir ou trancar uma porta' },
    { palavra: 'espelho', categoria: 'objeto', dica: 'reflete sua própria imagem' },
    { palavra: 'mochila', categoria: 'objeto', dica: 'carregada nas costas, cheia de compartimentos' },
    { palavra: 'boneco de neve', categoria: 'objeto', dica: 'feito de neve, tem cenoura no lugar do nariz' },

    // ── Lugares e monumentos famosos ──
    { palavra: 'castelo', categoria: 'lugar', dica: 'construção enorme com torres onde reis moravam' },
    { palavra: 'caverna', categoria: 'lugar', dica: 'buraco enorme dentro de uma montanha, bem escuro' },
    { palavra: 'praia', categoria: 'lugar', dica: 'lugar com areia e mar onde as pessoas vão se refrescar' },
    { palavra: 'labirinto', categoria: 'lugar', dica: 'lugar cheio de caminhos onde é fácil se perder' },
    { palavra: 'cassino', categoria: 'lugar', dica: 'lugar cheio de mesas de jogo e máquinas de apostar' },
    { palavra: 'montanha-russa', categoria: 'objeto', dica: 'brinquedo de parque cheio de subidas e descidas rápidas' },
    { palavra: 'torre eiffel', categoria: 'lugar', dica: 'torre de ferro enorme, símbolo de Paris' },
    { palavra: 'muralha da china', categoria: 'lugar', dica: 'muro gigantesco construído há séculos na Ásia, visível de longe' },
    { palavra: 'piramides do egito', categoria: 'lugar', dica: 'construções antigas em forma triangular, no meio do deserto' },
    { palavra: 'estatua da liberdade', categoria: 'lugar', dica: 'estátua enorme numa ilha nos Estados Unidos, segura uma tocha' },
    { palavra: 'coliseu', categoria: 'lugar', dica: 'antigo anfiteatro redondo na Itália, onde havia lutas de gladiadores' },
    { palavra: 'taj mahal', categoria: 'lugar', dica: 'palácio branco famoso na Índia, construído por amor' },
    { palavra: 'cristo redentor', categoria: 'lugar', dica: 'estátua enorme de braços abertos no alto de um morro no Brasil' },
    { palavra: 'machu picchu', categoria: 'lugar', dica: 'antiga cidade nas montanhas do Peru, construída pelos incas' },
    { palavra: 'monte everest', categoria: 'lugar', dica: 'a montanha mais alta do mundo' },
    { palavra: 'saara', categoria: 'lugar', dica: 'o maior deserto quente do mundo, na África' },
    { palavra: 'amazonia', categoria: 'lugar', dica: 'a maior floresta tropical do mundo, na América do Sul' },
    { palavra: 'veneza', categoria: 'lugar', dica: 'cidade italiana onde as ruas são canais de água' },

    // ── Pessoas e profissões ──
    { palavra: 'esqueleto', categoria: 'corpo', dica: 'o conjunto de ossos que sustenta o corpo' },
    { palavra: 'astronauta', categoria: 'pessoa', dica: 'pessoa que viaja pro espaço vestindo um traje especial' },
    { palavra: 'mergulhador', categoria: 'pessoa', dica: 'usa tanque de oxigênio pra explorar o fundo do mar' },
    { palavra: 'bombeiro', categoria: 'profissao', dica: 'profissional que apaga incêndios e faz resgates' },
    { palavra: 'professor', categoria: 'profissao', dica: 'pessoa que ensina numa escola' },
    { palavra: 'medico', categoria: 'profissao', dica: 'trata de doenças e cuida da saúde das pessoas' },
    { palavra: 'cozinheiro', categoria: 'profissao', dica: 'prepara pratos numa cozinha, geralmente de restaurante' },
    { palavra: 'pescador', categoria: 'profissao', dica: 'passa o dia tentando pegar peixes' },
    { palavra: 'cientista', categoria: 'profissao', dica: 'faz experiências e pesquisas em busca de descobertas' },
    { palavra: 'palhaco', categoria: 'profissao', dica: 'se veste de forma engraçada pra fazer rir em festas e circos' },
    { palavra: 'detetive', categoria: 'profissao', dica: 'investiga mistérios e crimes em busca de pistas' },
    { palavra: 'piloto de aviao', categoria: 'profissao', dica: 'profissional que comanda um avião' },

    // ── Filmes famosos (só o título, como resposta) ──
    { palavra: 'titanic', categoria: 'filme', dica: 'filme sobre um navio enorme que afunda no Oceano Atlântico em 1912' },
    { palavra: 'jurassic park', categoria: 'filme', dica: 'filme sobre um parque temático com dinossauros que fogem do controle' },
    { palavra: 'star wars', categoria: 'filme', dica: 'saga de ficção científica com naves, sabres de luz e uma "força"' },
    { palavra: 'o rei leao', categoria: 'filme', dica: 'animação sobre um filhote de leão que precisa assumir seu lugar na savana' },
    { palavra: 'harry potter', categoria: 'filme', dica: 'saga sobre um garoto bruxo que estuda numa escola de magia' },
    { palavra: 'matrix', categoria: 'filme', dica: 'filme sobre um mundo que na verdade é uma simulação de computador' },
    { palavra: 'shrek', categoria: 'filme', dica: 'animação sobre um ogro verde que mora num pântano' },
    { palavra: 'frozen', categoria: 'filme', dica: 'animação sobre duas irmãs princesas, uma delas com poderes de gelo' },
    { palavra: 'homem-aranha', categoria: 'filme', dica: 'herói que ganha poderes depois de ser picado por um inseto' },
    { palavra: 'batman', categoria: 'filme', dica: 'herói que veste uma fantasia de morcego pra proteger sua cidade' },
    { palavra: 'toy story', categoria: 'filme', dica: 'animação sobre brinquedos que ganham vida quando ninguém está olhando' },
    { palavra: 'avatar', categoria: 'filme', dica: 'filme de ficção científica passado numa lua alienígena chamada Pandora' },
    { palavra: 'os vingadores', categoria: 'filme', dica: 'filme onde vários heróis se juntam pra salvar o mundo' },
    { palavra: 'senhor dos aneis', categoria: 'filme', dica: 'saga de fantasia sobre a jornada pra destruir um anel poderoso' },
    { palavra: 'procurando nemo', categoria: 'filme', dica: 'animação sobre um peixinho perdido no oceano e seu pai à procura dele' },
    { palavra: 'king kong', categoria: 'filme', dica: 'filme sobre um gorila gigante que sobe num arranha-céu' },
    { palavra: 'piratas do caribe', categoria: 'filme', dica: 'saga sobre piratas e tesouros amaldiçoados no mar' },
    { palavra: 'de volta para o futuro', categoria: 'filme', dica: 'filme sobre um carro modificado pra viajar no tempo' },
    { palavra: 'indiana jones', categoria: 'filme', dica: 'aventureiro arqueólogo que usa chicote e chapéu' },
    { palavra: 'et', categoria: 'filme', dica: 'filme sobre um alienígena que fica amigo de uma criança na Terra' },

    // ── Jogos eletrônicos (só o nome, como resposta) ──
    { palavra: 'minecraft', categoria: 'jogo', dica: 'jogo onde tudo é feito de blocos que dá pra quebrar e construir' },
    { palavra: 'fortnite', categoria: 'jogo', dica: 'jogo onde 100 jogadores caem numa ilha e só um pode vencer' },
    { palavra: 'tetris', categoria: 'jogo', dica: 'jogo clássico de encaixar peças que caem, formando linhas' },
    { palavra: 'pac-man', categoria: 'jogo', dica: 'jogo clássico onde uma bolinha amarela come pontinhos fugindo de fantasmas' },
    { palavra: 'mario', categoria: 'jogo', dica: 'encanador italiano que salta em plataformas pra salvar uma princesa' },
    { palavra: 'sonic', categoria: 'jogo', dica: 'ouriço azul que corre extremamente rápido' },
    { palavra: 'pokemon', categoria: 'jogo', dica: 'franquia sobre treinadores que capturam e batalham com criaturas' },
    { palavra: 'among us', categoria: 'jogo', dica: 'jogo onde a tripulação precisa descobrir quem é o impostor' },
    { palavra: 'fifa', categoria: 'jogo', dica: 'um dos jogos de futebol mais famosos do mundo' },
    { palavra: 'call of duty', categoria: 'jogo', dica: 'franquia famosa de jogos de tiro em primeira pessoa' },
    { palavra: 'the sims', categoria: 'jogo', dica: 'jogo de simulação de vida onde você controla pessoas do dia a dia' },
    { palavra: 'roblox', categoria: 'jogo', dica: 'plataforma cheia de jogos criados pelos próprios jogadores' },
    { palavra: 'grand theft auto', categoria: 'jogo', dica: 'jogo de mundo aberto conhecido pelo apelido "GTA"' },
    { palavra: 'street fighter', categoria: 'jogo', dica: 'jogo clássico de luta um contra um' },
    { palavra: 'candy crush', categoria: 'jogo', dica: 'jogo de celular de combinar doces coloridos em fileiras' },

    // ── Cultura geral / artes ──
    { palavra: 'carnaval', categoria: 'cultura', dica: 'festa com desfiles, fantasias e muita música, famosa no Brasil' },
    { palavra: 'xadrez', categoria: 'cultura', dica: 'jogo de tabuleiro com rei, rainha, cavalo e peão' },
    { palavra: 'biblioteca', categoria: 'lugar', dica: 'lugar cheio de estantes de livros pra ler ou emprestar' },
    { palavra: 'museu', categoria: 'lugar', dica: 'lugar onde se expõem obras de arte ou objetos históricos' },
    { palavra: 'teatro', categoria: 'lugar', dica: 'lugar onde atores se apresentam ao vivo pro público' },
    { palavra: 'opera', categoria: 'cultura', dica: 'espetáculo onde a história inteira é cantada' },
    { palavra: 'orquestra', categoria: 'cultura', dica: 'grande grupo de músicos tocando instrumentos juntos' },
    { palavra: 'bale', categoria: 'cultura', dica: 'dança clássica feita na ponta dos pés' },
    { palavra: 'poesia', categoria: 'cultura', dica: 'texto escrito com ritmo e, às vezes, rimas' },
    { palavra: 'pintura a oleo', categoria: 'cultura', dica: 'técnica de arte feita com tinta grossa sobre uma tela' },
    { palavra: 'escultura', categoria: 'cultura', dica: 'obra de arte em três dimensões, feita de pedra, metal ou madeira' },
    { palavra: 'fotografia', categoria: 'cultura', dica: 'arte de capturar uma imagem com uma câmera' },
    { palavra: 'arquitetura', categoria: 'cultura', dica: 'a arte de projetar prédios e construções' },
    { palavra: 'origami', categoria: 'cultura', dica: 'arte japonesa de dobrar papel até formar uma figura' },

    // ── História ──
    { palavra: 'revolucao francesa', categoria: 'historia', dica: 'evento histórico na França que derrubou a monarquia, no século 18' },
    { palavra: 'imperio romano', categoria: 'historia', dica: 'um dos maiores impérios da história antiga, com capital em Roma' },
    { palavra: 'idade media', categoria: 'historia', dica: 'período histórico com castelos, cavaleiros e reis, entre a Antiguidade e o Renascimento' },
    { palavra: 'segunda guerra mundial', categoria: 'historia', dica: 'o maior conflito armado do século 20, terminou em 1945' },
    { palavra: 'egito antigo', categoria: 'historia', dica: 'antiga civilização conhecida pelas pirâmides e faraós' },
    { palavra: 'vikings', categoria: 'historia', dica: 'povo navegador do norte da Europa, famoso por seus barcos longos' },
    { palavra: 'descobrimentos maritimos', categoria: 'historia', dica: 'período em que navegadores europeus exploraram novas rotas pelo mar' },
    { palavra: 'revolucao industrial', categoria: 'historia', dica: 'época em que máquinas começaram a substituir o trabalho manual em fábricas' },
    { palavra: 'guerra fria', categoria: 'historia', dica: 'longa disputa de tensão entre duas grandes potências, sem confronto direto' },
    { palavra: 'gladiador', categoria: 'historia', dica: 'lutador que se apresentava em arenas na Roma Antiga' },
    { palavra: 'farao', categoria: 'historia', dica: 'título dado aos governantes do Egito Antigo' },
    { palavra: 'cavaleiro medieval', categoria: 'historia', dica: 'guerreiro que usava armadura pesada e lutava a cavalo' },
    { palavra: 'samurai', categoria: 'historia', dica: 'guerreiro tradicional japonês, seguia um rígido código de honra' },
    { palavra: 'mumia', categoria: 'historia', dica: 'corpo antigo preservado com faixas de tecido, comum no Egito Antigo' },

    // ── Ciência ──
    { palavra: 'dna', categoria: 'ciencia', dica: 'molécula que carrega as informações genéticas de um ser vivo' },
    { palavra: 'gravidade', categoria: 'ciencia', dica: 'força que puxa tudo pro chão' },
    { palavra: 'sistema solar', categoria: 'ciencia', dica: 'conjunto formado pelo sol e os planetas que giram ao redor dele' },
    { palavra: 'buraco negro', categoria: 'ciencia', dica: 'região do espaço tão densa que nem a luz consegue escapar' },
    { palavra: 'celula', categoria: 'ciencia', dica: 'a menor unidade viva que forma todos os seres vivos' },
    { palavra: 'oxigenio', categoria: 'ciencia', dica: 'gás essencial que respiramos pra viver' },
    { palavra: 'fotossintese', categoria: 'ciencia', dica: 'processo pelo qual as plantas transformam luz solar em energia' },
    { palavra: 'vacina', categoria: 'ciencia', dica: 'aplicada pra proteger o corpo contra uma doença' },
    { palavra: 'telescopio', categoria: 'ciencia', dica: 'aparelho usado pra observar estrelas e planetas distantes' },
    { palavra: 'microscopio', categoria: 'ciencia', dica: 'aparelho usado pra ver coisas pequenas demais a olho nu' },
    { palavra: 'energia solar', categoria: 'ciencia', dica: 'energia gerada a partir da luz do sol' },
    { palavra: 'clonagem', categoria: 'ciencia', dica: 'técnica científica de criar uma cópia genética idêntica de um ser vivo' },
    { palavra: 'big bang', categoria: 'ciencia', dica: 'teoria sobre a explosão gigante que teria dado origem ao universo' },
    { palavra: 'evolucao', categoria: 'ciencia', dica: 'processo pelo qual as espécies mudam ao longo de gerações' },
    { palavra: 'atomo', categoria: 'ciencia', dica: 'a menor partícula que forma toda a matéria' },

    // ── Esportes ──
    { palavra: 'basquete', categoria: 'esporte', dica: 'esporte onde se arremessa a bola numa cesta bem alta' },
    { palavra: 'natacao', categoria: 'esporte', dica: 'esporte praticado dentro da água, nadando o mais rápido possível' },
    { palavra: 'maratona', categoria: 'esporte', dica: 'corrida bem longa, de mais de 40 quilômetros' },
    { palavra: 'boxe', categoria: 'esporte', dica: 'esporte de luta com socos, usando luvas grandes' },
    { palavra: 'surfe', categoria: 'esporte', dica: 'esporte praticado em pé sobre uma prancha, em cima das ondas' },
    { palavra: 'ciclismo', categoria: 'esporte', dica: 'esporte praticado pedalando uma bicicleta' },
    { palavra: 'ginastica olimpica', categoria: 'esporte', dica: 'esporte com saltos, giros e muita flexibilidade, cheio de aparelhos' },
    { palavra: 'volei', categoria: 'esporte', dica: 'esporte de quadra onde a bola não pode tocar o chão do seu lado' },
    { palavra: 'skate', categoria: 'esporte', dica: 'praticado em pé sobre uma tábua com quatro rodinhas' },
    { palavra: 'esgrima', categoria: 'esporte', dica: 'esporte de luta com espadas finas, usando proteção no rosto' },
    { palavra: 'halterofilismo', categoria: 'esporte', dica: 'esporte de levantar o máximo de peso possível numa barra' },
    { palavra: 'patinacao no gelo', categoria: 'esporte', dica: 'esporte praticado deslizando sobre uma pista congelada' },

    // ── Comida ──
    { palavra: 'chocolate', categoria: 'comida', dica: 'doce escuro que derrete na boca, muita gente ama' },
    { palavra: 'pizza', categoria: 'comida', dica: 'massa redonda assada com molho, queijo e outros ingredientes por cima' },
    { palavra: 'sushi', categoria: 'comida', dica: 'prato japonês feito com arroz temperado e peixe cru' },
    { palavra: 'hamburguer', categoria: 'comida', dica: 'sanduíche com um disco de carne no meio do pão' },
    { palavra: 'sorvete', categoria: 'comida', dica: 'sobremesa gelada e cremosa, vem em vários sabores' },
    { palavra: 'pipoca', categoria: 'comida', dica: 'milho que estoura quando aquecido, clássico do cinema' },
    { palavra: 'churrasco', categoria: 'comida', dica: 'carne grelhada na brasa, tradição de fim de semana' },
    { palavra: 'feijoada', categoria: 'comida', dica: 'prato brasileiro feito com feijão preto e carnes' },
    { palavra: 'taco', categoria: 'comida', dica: 'comida mexicana feita com uma tortilha dobrada e recheio' },
    { palavra: 'croissant', categoria: 'comida', dica: 'pãozinho francês em formato de meia-lua, bem amanteigado' },
    { palavra: 'macarrao', categoria: 'comida', dica: 'massa comprida, muito usada na culinária italiana' },
    { palavra: 'queijo', categoria: 'comida', dica: 'feito a partir do leite, tem muitos tipos e sabores' },
    { palavra: 'mel', categoria: 'comida', dica: 'líquido doce e dourado produzido pelas abelhas' },
    { palavra: 'cafe', categoria: 'comida', dica: 'bebida quente e escura que ajuda a acordar de manhã' },

    // ── Tecnologia ──
    { palavra: 'internet', categoria: 'tecnologia', dica: 'rede mundial que conecta computadores e celulares do mundo todo' },
    { palavra: 'smartphone', categoria: 'tecnologia', dica: 'celular moderno que faz muito mais do que ligar' },
    { palavra: 'inteligencia artificial', categoria: 'tecnologia', dica: 'tecnologia que faz máquinas "pensarem" e responderem como gente' },
    { palavra: 'drone', categoria: 'tecnologia', dica: 'aparelho voador controlado remotamente, sem piloto a bordo' },
    { palavra: 'realidade virtual', categoria: 'tecnologia', dica: 'tecnologia que te transporta pra um mundo digital usando um óculos especial' },
    { palavra: 'codigo de barras', categoria: 'tecnologia', dica: 'aquelas listras pretas e brancas escaneadas no caixa do mercado' },
    { palavra: 'bluetooth', categoria: 'tecnologia', dica: 'tecnologia sem fio usada pra conectar fones e outros aparelhos por perto' },
    { palavra: 'impressora 3d', categoria: 'tecnologia', dica: 'máquina que "imprime" objetos sólidos camada por camada' },
    { palavra: 'satelite', categoria: 'tecnologia', dica: 'objeto que orbita a Terra, usado pra GPS e comunicação' },
    { palavra: 'criptomoeda', categoria: 'tecnologia', dica: 'dinheiro totalmente digital, sem nota nem moeda física' },
    { palavra: 'holograma', categoria: 'tecnologia', dica: 'imagem tridimensional projetada no ar, parece futurista' },
    { palavra: 'bateria', categoria: 'tecnologia', dica: 'armazena energia elétrica pra alimentar aparelhos sem fio' },
];

module.exports = { BANCO_30S };
